sudo: required
services:
- docker
script:
- make image
before_deploy:
- docker login -u $DOCKER_USER -p $DOCKER_PASS
deploy:
- provider: script
  script: make release
  on:
    branch: master
    tags: true
env:
  global:
  - secure: bBVA+RNw5pTT/t7jiQpkatLHzHzwG0Y1rt+SZNNCI9e0Y/jXQ/Tw160AquOI+kT7x7MCjGiwH+Mn6x9K7eg+/x3gLRuvGEhOnMdqhis2p5csUrkYNUG8pu49zil5/CjS4T0h3BSX4k7IGarLAGAvXJ/6H8MeOInfoU2fgcONnwFkGgMsyaw41DkqvH8g/vqlFwPQ6kLrahZtMCjkp0tR55W8UpOzJpioevQXx7BAvZdfFbUstF9rjCKClWs1elsLR+vcZxOz7kZIXbU6nEVN9cp32ZSflUnSE0REAjb6aJN03CFSuH+04EaXJzV/9S3cVoRMb3yFc11ty6H/NN9bqIvxClHANXE2F/MvB8oIOReyRYhK7lJsSTpWhm2z9mGd9tMyc8ctf4OU1BvfdDiB0ryxozY9jDFigTVOhttMKLPeQInvuupGBm0ThDwUxpAuDWsi7UwF83+x8ZTrQPSvfYmH9y/lpxzt/0GZdzyN/6Uvtm4L6AaNGFLNj7bVdWUKuS9aDB2pqJxkAUDCT0NcNftsMBGydTPrsGuJXkjJv97SJG4YtLZAAjxVdLmHzLWHIwnYH864NETeqeCu/iw+lXwdIEW2DA6ZzXmJaaRVTP8OM/eDyTOd1x+KAJYXFPH3Ud/GqXLMQz30exBNZDi7Oqz/Dg+DJczd0PTqYBtlSVs=
  - secure: hWbN1aPGhKG0r+szgBDdfDLwZPiEWsd7Mh8nPt5cUV/3cM8WntA2xZjbzOE74K0Z+bNMbH99zG1ar8AMgdgUySGL9UHLh/d80Ft7nXI1DE8uqi0PfYWZlLm5pUhXDMMRO3GkNidZwNfBu5YgIbXBkir8Ni7fftm6j+ILnXIgspWyjgz+nrp9Ygdi9RD8NpxX0uSRIrw7w+1RJXBbJx6vwhzf2G3DhIB6hwmF1CC0bcGAuyfBHsMVXlFOO1PCQYaF57GcfWjdgXGKWQXuHWMOErHEVEIpscY2fs0YARQNSoLZZnYKNJ92MYgh5AqFbUdCUpaW+RAzNu1fgC0IJlessal+U/XzIcL4TJsTufuO6ywBbbWr/eWiViT6SiVGVHE631ZvYtWbLq1GTBOK9UWc+t8Jv6l2G5bHjKXs9f1RNzUlXolkXB0bHVoy2X4dRsmNIhF4t0QcvhbQVYzX+frx6VeQWKeOEPrSUcrsUymq87D8wkxMkdV4HP5bAHNs64FpT305zd2IVoBRpMFcF3HJaoif4NTPTYmSq85j3/4FGdLaMUf2DNsST8kb8ZJQD+wOo8vCSt27kYjMtHgwrjgC9rE4PnXYuc+rbw6qP1/f3//klVhRV4QtLkWqsHcrUCnyqA4QUt7om7O09LLIPJJ7isgSbaaXC9nXHLn/OuhG2/o=
